# Generated by Django 5.2.5 on 2025-08-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_options_recipe_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking_time',
            new_name='film_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='resume',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
